# Generated by Django 5.1.7 on 2025-04-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Hydrogen', 'Hydrogen')], default='Petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Two-Door Sedan', 'Two-Door Sedan'), ('Hatchback', 'Hatchback (Liftback)'), ('Coupe', 'Coupe'), ('Limousine', 'Limousine'), ('Minivan', 'Minivan'), ('Hardtop', 'Hardtop'), ('Town Car', 'Town Car'), ('Kombi', 'Kombi'), ('Fastback', 'Fastback'), ('Phaeton', 'Phaeton'), ('Lando', 'Lando'), ('Targa', 'Targa'), ('Roadster', 'Roadster (Convertible, Spyder, Speedster)'), ('Torpedo', 'Torpedo'), ('Barchetta', 'Barchetta')], default='Sedan', max_length=30),
        ),
    ]
