# Generated by Django 5.1.7 on 2025-03-11 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('booking', 'Booking Report'), ('revenue', 'Revenue Report')], max_length=20)),
                ('generatedDate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
                ('totalBookings', models.IntegerField()),
                ('popularVehicles', models.TextField()),
            ],
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
                ('totalRevenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period', models.CharField(max_length=50)),
            ],
            bases=('reports.report',),
        ),
    ]
