# Generated by Django 5.1.7 on 2025-03-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admin_customer_fleetmanager_user_name'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetmanager',
            name='managedVehicles',
            field=models.ManyToManyField(blank=True, to='vehicles.vehicle'),
        ),
    ]
