# Generated by Django 5.1.7 on 2025-03-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fleetmanager_managedvehicles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='fleetmanager',
            options={'verbose_name': 'Fleet Manager', 'verbose_name_plural': 'Fleet Managers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
